CREATE TABLE Menu_Items (
	item_id SERIAL PRIMARY KEY,
	item_name VARCHAR(30) NOT NULL,
	item_price SMALLINT DEFAULT 0
);

INSERT INTO Menu_Items (item_name, item_price) VALUES
('Cheeseburger', 8),
('Veggie Burger', 7),
('Chicken Sandwich', 9),
('BLT Sandwich', 7),
('Grilled Cheese', 5),
('Club Sandwich', 10),
('Chicken Caesar Wrap', 9),
('Buffalo Chicken Wrap', 9),
('Steak Sandwich', 12),
('Turkey Sandwich', 8),
('Ham Sandwich', 7),
('Tuna Sandwich', 8),
('Egg Salad Sandwich', 6),
('Pulled Pork Sandwich', 10),
('Reuben Sandwich', 11),
('Philly Cheesesteak', 12),
('Fish Tacos', 10),
('Beef Tacos', 9),
('Chicken Tacos', 9),
('Veggie Tacos', 8),
('Shrimp Tacos', 11),
('Beef Burrito', 10),
('Chicken Burrito', 10),
('Veggie Burrito', 9),
('Shrimp Burrito', 12),
('Beef Quesadilla', 9),
('Chicken Quesadilla', 9),
('Veggie Quesadilla', 8),
('Shrimp Quesadilla', 11),
('Pepperoni Pizza', 12),
('Cheese Pizza', 10),
('Margherita Pizza', 11),
('BBQ Chicken Pizza', 13),
('Hawaiian Pizza', 12),
('Meat Lovers Pizza', 14),
('Veggie Pizza', 11),
('Supreme Pizza', 13),
('Mushroom Pizza', 11),
('Sausage Pizza', 12),
('Bacon Cheeseburger Pizza', 14),
('Spaghetti', 11),
('Fettuccine Alfredo', 12),
('Chicken Parmesan', 13),
('Lasagna', 13),
('Baked Ziti', 11),
('Eggplant Parmesan', 12),
('Shrimp Scampi', 14),
('Linguine with Clam Sauce', 13),
('Penne Arrabbiata', 12),
('Ravioli', 11),
('Gnocchi', 11),
('Carbonara', 13),
('Macaroni and Cheese', 10),
('Tortellini', 12),
('Chicken Marsala', 14),
('Veal Piccata', 15),
('Salmon Fillet', 16),
('Grilled Chicken Breast', 12),
('BBQ Ribs', 15),
('Beef Steak', 18),
('Pork Chop', 14),
('Lamb Chops', 17),
('Grilled Shrimp', 15),
('Fish and Chips', 13),
('Crab Cakes', 16),
('Lobster Roll', 18),
('Clam Chowder', 9),
('French Onion Soup', 8),
('Tomato Basil Soup', 7),
('Chicken Noodle Soup', 8),
('Minestrone Soup', 7),
('Garden Salad', 7),
('Caesar Salad', 8),
('Greek Salad', 8),
('Cobb Salad', 9),
('Chef Salad', 9),
('Taco Salad', 10),
('Spinach Salad', 8),
('Arugula Salad', 8),
('Caprese Salad', 9),
('Waldorf Salad', 9),
('Fruit Salad', 7),
('Mixed Green Salad', 7),
('Coleslaw', 5),
('Potato Salad', 6),
('Pasta Salad', 7),
('Macaroni Salad', 6),
('Cucumber Salad', 6),
('Quinoa Salad', 8),
('Roasted Vegetable Salad', 9),
('Apple Pie', 6),
('Pumpkin Pie', 6),
('Pecan Pie', 7),
('Cheesecake', 8),
('Chocolate Cake', 7),
('Carrot Cake', 7),
('Tiramisu', 8),
('Brownie Sundae', 8),
('Ice Cream Sundae', 7),
('Chocolate Chip Cookies', 5),
('Oatmeal Raisin Cookies', 5),
('Peanut Butter Cookies', 5),
('Lemon Bars', 6),
('Cupcakes', 5),
('Muffins', 5),
('Cinnamon Rolls', 6),
('Doughnuts', 5),
('Croissants', 4),
('Bagels', 4),
('Scones', 5),
('Biscotti', 5),
('Brownies', 5),
('Blondies', 5),
('Eclairs', 6),
('Cream Puffs', 6),
('Macarons', 7),
('Cannoli', 7),
('Baklava', 7),
('Profiteroles', 7),
('Fruit Tart', 7),
('Pavlova', 8),
('Churros', 5),
('Creme Brulee', 8),
('Panna Cotta', 8),
('Flan', 7),
('Bread Pudding', 6),
('Rice Pudding', 6),
('Banana Pudding', 6),
('Custard', 5),
('Gelato', 6),
('Sorbet', 5),
('Frozen Yogurt', 5),
('Smoothie', 5),
('Milkshake', 6),
('Iced Coffee', 4),
('Hot Coffee', 3),
('Latte', 4),
('Cappuccino', 4),
('Espresso', 3),
('Mocha', 4),
('Hot Chocolate', 3),
('Tea', 3),
('Iced Tea', 3),
('Lemonade', 3),
('Soft Drink', 2),
('Sparkling Water', 3),
('Bottled Water', 2),
('Fruit Juice', 4),
('Beer', 5),
('Wine', 6),
('Cocktail', 8),
('Martini', 8),
('Margarita', 8),
('Whiskey', 7),
('Vodka', 7),
('Rum', 7),
('Gin', 7),
('Tequila', 7),
('Brandy', 8),
('Scotch', 9),
('Bourbon', 8),
('Cognac', 9),
('Port Wine', 7),
('Sherry', 7),
('Champagne', 10),
('Sake', 7),
('Soju', 6),
('Sangria', 7),
('Mojito', 8),
('Pina Colada', 8),
('Long Island Iced Tea', 9),
('Bloody Mary', 8),
('Daiquiri', 7),
('Cosmopolitan', 8),
('Old Fashioned', 8),
('Mai Tai', 8),
('Negroni', 8),
('Moscow Mule', 8),
('Gin and Tonic', 7),
('Whiskey Sour', 8),
('Mint Julep', 8),
('Manhattan', 8),
('Sidecar', 8);

SELECT * FROM Menu_Items;

SELECT * FROM Menu_Items where item_name = 'Ravioli'
